services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: dm_api
    ports:
      - "8000:8000"
    environment:
      - THRESHOLD_TOPK=0.5
      - TARGET_K=5
    volumes:
      # monta os artefatos do modelo (gerados pelo train.py) como read-only
      - ./models/artifacts:/app/models/artifacts:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    container_name: dm_ui
    ports:
      - "8501:8501"
    environment:
      # dentro da rede do compose, o host "api" resolve para o serviço acima
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
